services:
  postgres:
    image: postgres:18
    container_name: small-data-engineering-postgres
    environment:
      POSTGRES_USER: smallde
      POSTGRES_PASSWORD: smallde
      POSTGRES_DB: smallde
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: